install:
    - ps: |
        # Here we nstall platyPS to the worker machine form the gallery
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
        Install-Module platyPS -Force
        Import-Module platyPS

build_script:
    - ps: |
        # TODO: create external help in en-US folder
        Import-Module platyPS
        New-ExternalHelp -OutputPath en-US -Path ./docs -force

test_script:
    - ps: |
        # TODO: load the Greet module and write a script
        # that will throw if docs are not up-to-date with the code.
        # In other words, if Update-MarkdownHelp changes the markdown.
        Import-Module platyPS
        Import-Module ./Greet.psm1
        $before = ((Get-ChildItem ./docs -Recurse | Measure-Object -Property Length -Sum -ErrorAction Stop).Sum)
Update-MarkdownHelp -Path ./docs -LogPath
        $after = ((Get-ChildItem ./docs -Recurse | Measure-Object -Property Length -Sum -ErrorAction Stop).Sum)
        if($before -ne $after){
           write-host "Failure" -ForegroundColor red
        }else{
           write-host "Success" -ForegroundColor green
        }        
